#ifndef _KYLIN_LIMITS_H_
#define _KYLIN_LIMITS_H_

#include <linux/limits.h>

#define KYLIN_PROC_NAME_MAX  32
#define KYLIN_PROC_PATH_MAX  PATH_MAX

#define KYLIN_MOD_NAME_MAX   32
#define KYLIN_MOD_CONT_MAX   512

#define KYLIN_TIMESTAMP_MAX  128

#define KYLIN_NAME_LENGTH        64
#define KYLIN_NAME_ULTRA_LENGTH  512
#define KYLIN_DESC_LENGTH        1024
#define KYLIN_DESC_ULTRA_LENGTH  65534

#endif /*_KYLIN_LIMITS_H_*/
