SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -DKYLIN_MODULE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -pthread

all: kylin_core_timer

LIB_OBJS = kylin_timer.o kylin_timer_source.o

kylin_core_timer: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o kylin_core_timer.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o kylin_core_timer.so


