SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -DKYLIN_MODULE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -lpthread

all: kylin_core_event

LIB_OBJS = kylin_event.o kylin_event_plugin.o 

ifeq (${KYLIN_OS}, Linux)
	LIB_OBJS += plugin/kylin_select.o plugin/kylin_poll.o plugin/kylin_epoll.o
else 
	LIB_OBJS += plugin/kylin_kqueue.o
endif

kylin_core_event: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o kylin_core_event.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o plugin/*.o kylin_core_event.so

