SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -I/usr/local/include -D_GNU_SOURCE -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -lbsd

all: libcore_core

LIB_OBJS = kylin_core.o kylin_core_module.o kylin_core_module_elf.o 

libcore_core: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o libcore_core.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o libcore_core.so

