SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -DKYLIN_MODULE -D_GNU_SOURCE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib

all: kylin_core_shm

LIB_OBJS = kylin_shm.o kylin_shm_obj.o kylin_shm_open.o

kylin_core_shm: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o kylin_core_shm.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o kylin_core_shm.so


