SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -I/usr/local/include -D_GNU_SOURCE -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib

all: libcore_shm

LIB_OBJS = kylin_shm.o kylin_shm_obj.o kylin_shm_open.o

libcore_shm: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o libcore_shm.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o libcore_shm.so

