SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -DKYLIN_MODULE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -lpthread

all: kylin_core_log

LIB_OBJS = plugin/kylin_log_console.o plugin/kylin_log_file.o plugin/kylin_log_system.o \
		   kylin_log.o kylin_log_buf.o kylin_log_obj.o

kylin_core_log: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o kylin_core_log.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o plugin/*.o kylin_core_log.so


