SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -D_GNU_SOURCE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -pthread

all: libcore_thread

LIB_OBJS = kylin_thread.o kylin_thread_impl.o 

libcore_thread: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o libcore_thread.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o libcore_thread.so

