SHELL=/bin/sh
# Where you want it installed when you do 'make install'
PREFIX=/usr/local/

CFLAGS = ${KYLIN_CFLAGS} -DKYLIN_MODULE -D_GNU_SOURCE -I/usr/local/include -I${KYLIN_LIB_SRC}
LDFLAGS += -L/usr/local/lib -pthread

all: kylin_core_thread

LIB_OBJS = kylin_thread.o kylin_thread_impl.o

kylin_core_thread: $(LIB_OBJS)
	${CC} ${CFLAGS} ${LIB_OBJS} -shared -o kylin_core_thread.so ${LDFLAGS}

distclean: clean
clean:
	rm -f *.o kylin_core_thread.so


